name: Manual Project Deploy
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch (default: master)'
        required: false
        default: 'master'
jobs:
  deploy:
    runs-on: production
    concurrency:
      group: deploy_servers
      cancel-in-progress: true
    env:
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      host: ${{ vars.HOST }}
      database_url: ${{ vars.DATABASE_URL }}
      next_public_supabase_url: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
      next_public_supabase_anon_key: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      service_role_key: ${{ secrets.SERVICE_ROLE_KEY }}
      pw: ${{ secrets.PW }}
      db_host: database
      db_port: 5432
      db_name: duke
      db_user: postgres
      db_password: postgres
    steps:
      - name: Check tree command installation
        id: tree_check
        continue-on-error: true
        run: which tree
      - name: Install tree command
        if: ${{ steps.tree_check.outcome == 'failure' }}
        run: sudo apt-get install tree
      - name: Display tree before cleanup
        run: tree -I venv
      - name: Display working directory before cleanup
        run: pwd
      - name: Check Docker Engine installation
        id: docker_check
        continue-on-error: true
        run: which docker
      - name: Install Docker Engine
        if: ${{ steps.docker_check.outcome == 'failure' }}
        run: curl -fsSL https://get.docker.com/ | sh
      - name: Stop previous project execution
        continue-on-error: true
        run: docker compose down
      - name: Cleanup project directory
        run: rm -rf ${{ github.workspace }}/*
      - name: Display tree after cleanup
        run: tree
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.target_branch }}
      - run: |
          git submodule update --init --recursive
          git submodule update --recursive --checkout
      - name: Display tree after project setup
        run: tree
      - name: Create .env.local file
        run: |
          echo 'OPENAI_API_KEY="${{ secrets.openai_api_key }}"' >> duke-frontend/duke-chat/.env.local
          echo "NEXT_PUBLIC_BACKEND_BASE_URL=https://${{ vars.host }}" >> duke-frontend/duke-chat/.env.local
          echo "DATABASE_URL=${{ vars.database_url }}" >> duke-frontend/duke-chat/.env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ vars.next_public_supabase_url }}" >> duke-frontend/duke-chat/.env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.next_public_supabase_anon_key }}" >> duke-frontend/duke-chat/.env.local
          echo "SERVICE_ROLE_KEY=${{ secrets.service_role_key }}" >> duke-frontend/duke-chat/.env.local
          echo "PW=${{ secrets.pw }}" >> duke-frontend/duke-chat/.env.local
          echo "NODE_ENV=production" >> duke-frontend/duke-chat/.env.local
          echo "NEXT_PUBLIC_SITE_URL=" >> duke-frontend/duke-chat/.env.local
      - name: Build project
        run: docker compose build --no-cache
      - name: Run project
        run: docker compose up -d
