name: Stop project
on:
  workflow_dispatch:
jobs:
  stop_and_destroy:
    runs-on: production
    concurrency:
      group: deploy_servers
      cancel-in-progress: true
    steps:
      - name: Check tree command installation
        id: tree_check
        continue-on-error: true
        run: which tree
      - name: Install tree command
        if: ${{ steps.tree_check.outcome == 'failure' }}
        run: sudo apt-get install tree
      - name: Display tree before cleanup
        run: tree -I venv
      - name: Display working directory before cleanup
        run: pwd
      - name: Stop previous project execution
        continue-on-error: true
        run: docker compose down -v
      - name: Cleanup project directory
        run: |
          rm -rf ${{ github.workspace }}/*
      - name: Display tree after cleanup
        run: tree
